{
  "version": "v1alpha1",
  "debug": false,
  "persist": true,
  "machine": {
    "type": "controlplane",
    "token": "d980bn.20dzyjfejcmb2548",
    "ca": {
      "crt": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQekNCOHFBREFnRUNBaEVBMnNnT2R6MityTCtCdHFyYjZRQ0FHVEFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qUXdOakUwTVRZeE9EVXpXaGNOTXpRd05qRXlNVFl4T0RVeldqQVFNUTR3REFZRApWUVFLRXdWMFlXeHZjekFxTUFVR0F5dGxjQU1oQURRMTNkM0x1STNiQ0JqYUxqdSttNDlCN3k0eHRDZ0Ewb0pjCmljMS9Ldnh3bzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRk4wNktKNHd2aVNybmQ1dQpxbW5lc0lmWUhwWDNNQVVHQXl0bGNBTkJBTzhWdDAyeGZ6OXE4eGhVeG1UZzBpc2JLVURLVmFyeVlNdXNFb3dMCnRHRE5qbURtUEtXbXo2S3cvcHZMbnRna3dTS0ZDT1dqaHhaNlpXZ082OGRNZFF3PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==",
      "key": "LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJRDdCOE56NWtWMmdPVzBSZndiNkZnYW9hdGNMejlRWHY5QzJIODNxOTRMcwotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K"
    },
    "certSANs": [],
    "kubelet": {
      "image": "ghcr.io/siderolabs/kubelet:v1.30.1",
      "defaultRuntimeSeccompProfileEnabled": true,
      "disableManifestsDirectory": true
    },
    "network": {},
    "install": {
      "disk": "/dev/mmcblk0",
      "image": "ghcr.io/siderolabs/installer:v1.7.4",
      "wipe": false
    },
    "features": {
      "rbac": true,
      "stableHostname": true,
      "apidCheckExtKeyUsage": true,
      "diskQuotaSupport": true,
      "kubePrism": {
        "enabled": true,
        "port": 7445
      },
      "hostDNS": {
        "enabled": true
      }
    }
  },
  "cluster": {
    "id": "rkBj45UCN5eCYCUqBsNT5rINfCVdNqTC0xW1NkmI_Nk=",
    "secret": "ahVpA6jcnbD/mWJb6zaB8QaJ4o1Ssz8G4Hb8TDMNr5w=",
    "controlPlane": {
      "endpoint": "https://192.168.90.50:6443/"
    },
    "clusterName": "rpi4-sidero",
    "network": {
      "dnsDomain": "cluster.local",
      "podSubnets": [
        "10.244.0.0/16"
      ],
      "serviceSubnets": [
        "10.96.0.0/12"
      ]
    },
    "token": "tiezc7.evsck9th7f17s0fh",
    "secretboxEncryptionSecret": "PmIiWlCp2e7iE04KYPXZP57+aCzw1KJ3/z5QhoOOaXE=",
    "ca": {
      "crt": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpVENDQVMrZ0F3SUJBZ0lRWHJLN2FJQldVNUF6SE9UVWlpQ2V4ekFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTBNRFl4TkRFMk1UZzFNMW9YRFRNME1EWXhNakUyTVRnMQpNMW93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCSFNBK0huTDN5VTJBVmt3YllKeGp4ZVpWOE1XQy9zZGtNY0hlb28wREV4R0pBdlRpV3A0WWtWWVhFL2gKd2poZUhEN0s0ckpxeHJaLzdoUzhqdy9NSEV1allUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVVSMU9rNWZ3c05QVFB2bjUySlhueFUwNWxoNlV3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnQlpveXNRRnYKWFl5eDFsTTZFMUN3WGZQRE5ZOGowTzdZb1QxalovRE9vS2tDSVFDd1dWNGlTV1VHUUdFN1crWm5HbCtBTWJ5VgpyMGdiMERxcVQ3Ui9QOGVURkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==",
      "key": "LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU1lc201TGI4bkU4MFh0WkozdDdsdU1tUzFGVkhOZHY4RDNHb3htVHYyWjJvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFZElENGVjdmZKVFlCV1RCdGduR1BGNWxYd3hZTCt4MlF4d2Q2aWpRTVRFWWtDOU9KYW5oaQpSVmhjVCtIQ09GNGNQc3Jpc21yR3RuL3VGTHlQRDh3Y1N3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo="
    },
    "aggregatorCA": {
      "crt": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJYekNDQVFXZ0F3SUJBZ0lRYmZWTnJPd09aeGhLVTdLb0xhSTAvVEFLQmdncWhrak9QUVFEQWpBQU1CNFgKRFRJME1EWXhOREUyTVRnMU0xb1hEVE0wTURZeE1qRTJNVGcxTTFvd0FEQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5QXdFSEEwSUFCT2VzUnA5ZTBOb2tpa1RtZ3E4YmhpSUJhWmdiNkgxM0FjeVV0LzVkbURDbXZRbkNhZDJECjhHbncyZ2duVUcrNlpFa0hwUExabWh1WmRrOFltYWVHbStpallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWQKQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZApCZ05WSFE0RUZnUVVSYVYyQU1BMUhXL2lKVEYyeEdLeS9XejZ5V2t3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloCkFQNmlKTEFIKzdvL0oyQ0V2eHdySVdMZlk3cWlabFlnQlpRUTNpT2lYUXp3QWlBNzgxMTNoU2ZidUwrcDMrZU0KRmdrUXpVVDBqS29mbWJhcjE3aWpGVHk2WGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==",
      "key": "LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUZmVEh0SnZscXBPY3N5aVJHTUhpYW51VHlJN3VQL1ArekVOMWZaZzZWd3hvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFNTZ4R24xN1EyaVNLUk9hQ3J4dUdJZ0ZwbUJ2b2ZYY0J6SlMzL2wyWU1LYTlDY0pwM1lQdwphZkRhQ0NkUWI3cGtTUWVrOHRtYUc1bDJUeGlacDRhYjZBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo="
    },
    "serviceAccount": {
      "key": "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS0FJQkFBS0NBZ0VBb3U5V0RoRTFobk85c0JVeGhtMERnM3l4U3FWTDJPakhQUFlvM1R0K2xONTIzbzNhCm1IQ0Z6NDNteGJZd1ZXV2VpR1RHeVB1NUV2SjBYVnhoWTZYaEova1BXU1hrNlRGRm9DNmp0UUV6em10dEwzMi8KVzB4emlpN2U4WFNMeGFqZkM3Z3FjU09xTnkwdmtUazd5dlVVOGs5QXY5UkpBa20vbXRxRXVQUFVOSW5NVmptTgplZmFiRlN4TVhRSmdGK3V1VmlsRUx0WWtBQjRReEc0anpVTi8xZ2xmOElOVkYzUWpJcUZZK05XeGw5U0ExaTZxCmswZm1vTHZ1WmRDMTNjdlFjcW14Tk1zMFZSejN5dCsyVnZZSlhSNENaOVR6V1d4YnZvM0RpQ0NMTkRoYW1QOE4KeHIyaGRobUwrZzNNQTVxVklGM0RjZytDZTNDMlVpSjJuc25ESTE1QmlKZFFVWHpyUCtsQ2pPZzlFbldsTjFxVApZRlc4N3ZjWGp1aHFSeUVQSG01WlhOeEFYZFVTT2puRTZ2YWpJQm5TUUV5N1BOSEhXajJ6NkZpK3pyanZOVFZ3CnZLQ0VKaDlyei96VnVoNDM0b3NyaXc2MVVsd09SQ2xEVHAvbHg4azh2UHJUOGg4ZW5obTBBaWpqRlFDTFgwSC8KY0s1K01uRktDdjQ5OFNnWGlRYkhKQmQzanhNeXBRaVJJOHI5MXZERWpFVDE0TUYySmtnS2xYVFlwNXJ0dHNQKwpQMXF2aFNCWmNabmYxWVpNTDV2UFYzOTNVK2o4YjNGSHVoc2NsU3krNzJnNlNNLy92Y3NiVDZPeHJQb2N4MjJWCmJCQlY0T0tZZVMwTVlDc2xIQjdENm9RSEg4R2UwbWQxdHpvMWRFQUJGZmY0VHpCekNTOUtQOUxUNzRFQ0F3RUEKQVFLQ0FnQkF3SGJsbmtjMFNMa0F5bHRsUGR1Z25LUmtzdTVDcExmUmJVNXVKViszei9WVG12SmRsSkpKR3U2MApjaVFoUEFKVjJCNzc3clh0WnJlQ0J0MlpXV255bGROWXJXdWNsUDFEbkdWbzRMSnkvVlJtQkVaUkJVQUJrWUQrCldqL1Y3TGUvazVBaWFIY1QrSHduN2FQcWs1Mmdjb2liODhTVUNUVUJXSWhZYkdaUC90ZGJDUUpGanhDd3lHc00KcDQ0QzA2SDBFZkJMNE1ScjI0YjBXWVVXNVJWZnZWZ0lZRmtudWZyZ24xaVpnMnRSbUowZkFXcStuMXR6VTF4NQowQWtHdlNINC82RXlCdk9rUTUvaVd5ZSt4WWFSSUFUNnVMR0JQMFB5cGFvb1ppNk1NVDBvQW15Nko5Q0wrN2thClJmTm5GejdlbndTMlJwMm5hdks2RDRJdXRxWTZ2S0Jta1VpSDZMUWNhV1F1ZUkvVTBOM1JKNkU4cnlUdFRRalYKUVZkRTJ6ajlXVWgxeW5lNlI4NlRYbjhXaHhQOXlqN3h5eFplWTdCVFJ0cmllbzVLYmt3N1VtangrN3g5NXZiTwpZSDNKV3FZZklaWTBtMDRzRnlyOWp3TEg3R0g3c3puLzVpUEZpYmtGcGxRdDhCRzFSZE9UcFNtZXZMT3JTcXY3Cnp5ZnV0VENmM3MwUEJIelVzRHJPU2hlelhoNGtYKzZnRW1OZjA1M3V1SlJGYmhOeUpFVWdpYlJ6WjNlQVZTNUcKeHNkR01kRW9vSkhVNHF2eWxLZEgwMHVuMHdiUnFsWXdBdmo0c3FzekNHVHhidEUwZU1zaVpxNGlvMmw0aXJEMQo4YW0xOEVNcE93NG1Ra1N6UG5PQ0tTYTdoaDdqa0R1Y1VvZ2dmNE1rTTc1ZU5CdVV3UUtDQVFFQTAvSzAzVnI2Cmc4c3ExOVlXOXFibGZ6RytzdGlRc0xRSGJYU2d6YVgreUF1Q1ZYNmpSWHpRY0dGVEwreCtmQlJmSDlISytvcG0KeGtmRlpIUlpjZDgxQ1NCdHVGMzlxWllVcGltUWI0OUZQMTBkQm14ODBIYi85N1BOVDN0NytqV05zSnNITURCRwptbDh4ZDB3NUNPVUFnQytwZnphazVRS3B2UHBhKzhocVN6ZmdPS3JwSEVJMkl2NFZ0Njl3M2xZMm0vdEhBcjdnClMzWUhIeFNCc2MrSmdHZk1aTGk5UWJmR1gyc0llaFUrdVRyYUNZRENURWFoMlZhbkhuL2dpWWNKeXVKQTNpaTMKN0hxYm1uaXRoeEN0aTE5bGNaUEl4WXZzcm40VXZSTEtiTTlrQXNZR2p0QjhSNjFWRUpaRk1ZOTdSanZhYmVtTApNbUJoSUZUR0RBK2EyUUtDQVFFQXhNeS9ESXEyR09jYUJGcmJxd0txZmw4K0kwN0VId1NzYlBHaEVtV2dRN25ICkJ6Rjhic1ladlFibFcySXJTazBnUFAvMDVLYzVNMk5JbnpJZVZZMUZoaHNpd1hPeVhlS3pFZktSNHoxQ0NpMUEKQXgzRWNPQWlsdXhyZlByMFpoMUtUKzd5UDg1U1lnNGg2T2xaekRQYUdla2JmcndPOTAvVmJXR3BDaFJIVTNXQgpDc1JBWkVzUmJrSmExdExOb2NxQlRNUUFpSDBqOUQwUEg2Y3l2KzVLcm5xQmVpb0dXL2xVWUQ3dzg5ckhKbEthCjhEMVVCSm9LdEVsOTgwNDBCNGNNckZ2SjhQL2k5ekx4K09KM0pDUlUrY0hYNEgvS3NSbHV6UUtXK1FRbnVlYWkKbkdMWHJWcGN5eUpzUW5mMUpXb0hHVlNCcXpkL1ROWmJoU0VKK2FBQTZRS0NBUUVBanpaUlJieml4MGp4c3hQRApRbmkxVzhQR0lseTVMOTBGbzgwSmxzdVNJNk83Tm4reVhSS2dXVDg2RVlqUVVwRUZVWi9WY29Nd1BNeGtNYU40CmlMd1V2d3o5ZG5WMElESDcwK2NENUkyL2NiZytFNGdjc2xPbVU3NVhmVnhvQWtKTGNramVpNDRqTnM0Wnc0MXEKZ0hzVVlvbFNFMVplQnl4TWV4Z0RnRndFanJ5N3NpNnlBdGt1Y1dpVVRpQ3F1R0V5MXlUcjc0d0FUSno4NU9CYgpYa1ZvbUs0S2F3aDFRVUduTmZSQnJ4Uko1S2xDaU9kSzRuVmJpVnJHNDVIdXE1N21YQU9UWjBuR05YRUhVVkkzCmxxc0xTTUIxOEUrMmV0MDRXUk55ZWV1SGdneUVmR2RJS1JudzBCSHNCNkF5TXZITGowS0VMbjUvQXRRaTdOQzcKWFl6eHlRS0NBUUJGdDhjQ3VXMHpPME96UVVES3YySUk3TkxGalZUYkxEdXRTSmhvUFFwZWs4VFhYb2VYY3FTUgptNHpMSitid0pveUNMNmJoRGdDc25NS1FheC9sN09zeFRCR3UrTDY2bGVJY1BKUEVMZUprV28xdnpTN1hVZi9PCithaEdtVnpWaEJEY2FtajFnN0VadmFuenFoOCt3U3ZGdkJnYWVLTFFxRDZTeG1NdEIrd1F1L0xnRHBCRk4zYlEKV2I5MmxTMTE0SmlYeW1QcDluTXpSaUpDYzJmK0tIdmFmZG02bm9Lc09KTFVtZGVnZStQTFJyNU8xMXNaV2p6cQppNUtNREN0UWMxNWcvUTk0U2g1c3RtYVVaaDRROXJJSDNNME9ZaGM3VUNnNWhtNVhmMHBYaUVZWklzY0hTWmpQCitiemllejZrWjRCbVQ5SzBCakFaMTJLS3NoNm5pVEJwQW9JQkFFTWk3WGQxVzdPQXhnRitxTFlIWjVEb3dlM04KR0ZGNHBUWEhrNmJPblR2R2tmbWVEa1puS24wS3ZKVGNXTUpwM0dpc0pvSnFmU0tPdEt4aCt1UjhrMVZGczkxUgpvb2pEQUZEaDlqS04wS3M4T2JFY3B0SkhiVlBRL0xwTE90Y015cmd5RVE3U3haZmNteEtncHAySXovSkhwSFhKCnIxR1g3a1gvNHJhZG1pdFdnSjgrTVlZVFN1dnpxMTRKVHFYS0IvTWFlSG9UNk0wTmYwWXIycE5ob0IrcWFBUUEKVlhYNDl5VU8xRERwTzJ4aEljZklYSTZTTEUrOW0rdmlxTWxlZWduRHJEa1Z2R0pSSEk2aDJCQnN0UEtUU2tMTgprM2JyNEVwWW9mbzhIbWZLbFFDalF0NVY0SmNhb2wramw2L1g2cURxakVsM1h6TEoveiswMFltWHFIYz0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K"
    },
    "apiServer": {
      "image": "registry.k8s.io/kube-apiserver:v1.30.1",
      "certSANs": [
        "192.168.90.50"
      ],
      "disablePodSecurityPolicy": true,
      "admissionControl": [
        {
          "name": "PodSecurity",
          "configuration": {
            "apiVersion": "pod-security.admission.config.k8s.io/v1alpha1",
            "defaults": {
              "audit": "restricted",
              "audit-version": "latest",
              "enforce": "baseline",
              "enforce-version": "latest",
              "warn": "restricted",
              "warn-version": "latest"
            },
            "exemptions": {
              "namespaces": [
                "kube-system",
                "sidero-system",
                "cabpt-system"
              ],
              "runtimeClasses": [],
              "usernames": []
            },
            "kind": "PodSecurityConfiguration"
          }
        }
      ],
      "auditPolicy": {
        "apiVersion": "audit.k8s.io/v1",
        "kind": "Policy",
        "rules": [
          {
            "level": "Metadata"
          }
        ]
      }
    },
    "controllerManager": {
      "image": "registry.k8s.io/kube-controller-manager:v1.30.1"
    },
    "proxy": {
      "image": "registry.k8s.io/kube-proxy:v1.30.1"
    },
    "scheduler": {
      "image": "registry.k8s.io/kube-scheduler:v1.30.1"
    },
    "discovery": {
      "enabled": true,
      "registries": {
        "kubernetes": {
          "disabled": true
        },
        "service": {}
      }
    },
    "etcd": {
      "ca": {
        "crt": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmakNDQVNTZ0F3SUJBZ0lSQU1lWUVFVzJPcWJUbHBoUWhLZDVPNkV3Q2dZSUtvWkl6ajBFQXdJd0R6RU4KTUFzR0ExVUVDaE1FWlhSalpEQWVGdzB5TkRBMk1UUXhOakU0TlROYUZ3MHpOREEyTVRJeE5qRTROVE5hTUE4eApEVEFMQmdOVkJBb1RCR1YwWTJRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFTZXY1RmljOUxKCmFtdW1VYlp3bk9xdS9NYUhTV2p3YTluajA3RlJ5dDl4NUxMS1Y2a205ZGFqa0pNVXpocU9zN3N2eG5veW5LaGkKK2NrS1NKYTdTSmtlbzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSApBd0VHQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkp1R1hEMDdkV0NBCjFMRWpFRVlJalYreUlXMFhNQW9HQ0NxR1NNNDlCQU1DQTBnQU1FVUNJRmhxSTNvT00wc3BEM2ZaRENYd0Q1YXYKUXR5a2hod1FYL1VlSmNkTmNtNG1BaUVBcDFnRENZRmFIRmxxMkZSbWg0NDVKSHRrcWJUek9OOHNqM0x6S09Jcgp0ejA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K",
        "key": "LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUZFcFJkZmtMRlVTWjJUbm80NnVWbHA3QWViaVVIYVlOZGZ4ZVAwU0Zya1pvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFbnIrUlluUFN5V3BycGxHMmNKenFydnpHaDBsbzhHdlo0OU94VWNyZmNlU3l5bGVwSnZYVwpvNUNURk00YWpyTzdMOFo2TXB5b1l2bkpDa2lXdTBpWkhnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo="
      }
    },
    "allowSchedulingOnControlPlanes": true
  }
}
